# Generated by Django 4.0.2 on 2022-02-05 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interviewers', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='interviewer',
            options={'ordering': ['start_time']},
        ),
        migrations.RemoveField(
            model_name='interviewer',
            name='date',
        ),
        migrations.AlterField(
            model_name='interviewer',
            name='end_time',
            field=models.DateTimeField(verbose_name='End time'),
        ),
        migrations.AlterField(
            model_name='interviewer',
            name='start_time',
            field=models.DateTimeField(verbose_name='Start time'),
        ),
    ]
