# Generated by Django 4.0.2 on 2022-02-05 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interviewers', '0002_alter_interviewer_options_remove_interviewer_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interviewer',
            name='end_time',
            field=models.DateTimeField(default=False, verbose_name='End time'),
        ),
        migrations.AlterField(
            model_name='interviewer',
            name='start_time',
            field=models.DateTimeField(default=False, verbose_name='Start time'),
        ),
    ]
