# Generated by Django 4.0.2 on 2022-02-05 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default=False, max_length=254)),
                ('user_id', models.CharField(default=False, max_length=254)),
                ('start_time', models.DateTimeField(default=False, verbose_name='Start time')),
                ('end_time', models.DateTimeField(default=False, verbose_name='End time')),
            ],
            options={
                'ordering': ['start_time'],
            },
        ),
    ]
